### ISSUE TITLE
DB Syncronization

### ISSUE THREAD

**Issue by hyeonho9877** [UdangtangtangYMC/emotion_map#13]
Remove Temperature value from DB
cal temperature by given happy_people, angry_people
set value to db

**Comment by wsm9175** [comment]
DB Syncronization #13 Issue 해결 내용

commit message - Troubleshooting DB Syncronization

1. City 클래스의 changeStatus메서드 안의 temperature가 들어간 모든 함수 제거

2. City 클래스의 getStatistics 메서드 안의 자신의 위치에 해당하는 정보가 DB에 없는 경우 temperature 속성 setValue 제거

3. DB에 아무 데이터도 존재하지 않는 경우에 대해
temperature 속성 setValue 제거

4.MainPresenter StatisticsCallBack implement
 teperature 항목은 get -> angry_people - happy_people로 값 초기화

5.FireBase - DB - Status - City - Temperature 항목 삭제

6. 동시 테스트 성공
