### ISSUE TITLE
Kakao Email

### ISSUE THREAD

**Issue by hyeonho9877** [UdangtangtangYMC/emotion_map#14]
when customer doesn't agree with email access permission

**Comment by wsm9175** [comment]
KAKAO Email #14 issue
commit message : Troubleshooting Kakao Email Permission check
solution : 이메일 정보 제공을 동의 하지 않은 사용자에 대해 최근 내 상태, Add_emotion 기능을 제공하지 않는다
1City class -  addMYCommentListener 
Add if Id == null then callback.onSuccess(comment1, comment2)
